name: Project Harbor
description: |
  (Experimental) Enterprise Class Container Registry [by VMware]
version: 1.8.0
category: Private Container Registry
projectURL: https://github.com/vmware/harbor 
license: Apache License 2.0 
